---
# tasks file for deploy-osh
- name: Load variables
  include_vars: "{{ item }}"
  loop:
    - "{{ playbook_dir }}/../vars/common-vars.yml"
    - "{{ playbook_dir }}/../vars/manifest.yml"
  tags:
    - always

- name: Get ses_cluster_configuration
  include_vars: "{{ socok8s_ses_pools_details }}"
  tags:
    - always

- name: Pre-fligt checks for the role
  assert:
    that:
      - ceph_admin_keyring_b64key is defined
      - ceph_user_keyring_b64key is defined
      - suse_osh_deploy_vip_with_cidr is defined
  tags:
    - always

- name: Decode the secrets
  set_fact:
    ceph_admin_keyring_key: "{{ ceph_admin_keyring_b64key | b64decode }}"
    ceph_user_keyring_key: "{{ ceph_user_keyring_b64key | b64decode }}"
  no_log: True
  tags:
    - always

- name: Create a list of monitors (ip and port) if no override exists for it.
  set_fact:
    suse_osh_deploy_ceph_mons: "[{{ ses_cluster_configuration['conf_options']['ses_mon_host'] }}:{{ ceph_mon_port | default(6789) }}]"
  when: suse_osh_deploy_ceph_mons is not defined
  tags:
    - always
    - run

- name: Install system packages
  package:
    name: "{{ suse_osh_deploy_packages }}"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
    - install

- name: Ensure kubectl is installed
  include: kubectl-install.yml
  tags:
    - install

- name: Ensure helm and tiller are up to date
  include: helm-install.yml
  tags:
    - install

# TODO(evrardjp): Replace this with systemd service
- name: Ensure helm runs on localhost
  include: helm-run.yml
  tags:
    - run

- name: Enrol nodes for CCP
  include: enroll-caasp-nodes-for-osh.yml
  tags:
    - run

- name: Ensure VIP is present in /etc/hosts for the services to deploy
  blockinfile:
    path: /etc/hosts
    block: |
      {{ suse_osh_deploy_vip_with_cidr | ipaddr('address') }} keystone keystone.openstack.svc.cluster.local
      {{ suse_osh_deploy_vip_with_cidr | ipaddr('address') }} glance glance.openstack.svc.cluster.local
      {{ suse_osh_deploy_vip_with_cidr | ipaddr('address') }} cinder cinder.openstack.svc.cluster.local
      {{ suse_osh_deploy_vip_with_cidr | ipaddr('address') }} nova nova.openstack.svc.cluster.local
      {{ suse_osh_deploy_vip_with_cidr | ipaddr('address') }} neutron neutron.openstack.svc.cluster.local
      {{ suse_osh_deploy_vip_with_cidr | ipaddr('address') }} neutron-server neutron-server.openstack.svc.cluster.local
      {{ suse_osh_deploy_vip_with_cidr | ipaddr('address') }} horizon horizon.openstack.svc.cluster.local
      {{ suse_osh_deploy_vip_with_cidr | ipaddr('address') }} heat heat.openstack.svc.cluster.local

# Developers have patched code, and don't need fetching product sources
- name: Fetch OSH code
  include_tasks: code-install.yml
  when:
    - not developer_mode
  tags:
    - install

# NOTE: This task should stay close to code-install, so that no race condition
# happens between the git-cloning, an eventual failure, and the building of the charts.
- name: Build infra charts
  make:
    chdir: /opt/openstack-helm-infra
    target: all
  tags:
    - install

- name: Build openstack charts
  make:
    chdir: /opt/openstack-helm
    target: all
  tags:
    - install

- name: Apply base configuration in K8s for deployments on top of CaaSP/SES
  include_tasks: apply_on_k8s.yml
  loop:
    - action: create openstack namespace
      template_src_file: k8s-openstack-namespace.yml.j2
      templated_location: /tmp/socok8s-openstack-namespace.yml
    - action: create privileged ClusterRoleBinding for ServiceAccounts
      template_src_file: k8s-privileged-cluster-role-binding.yml.j2
      templated_location: /tmp/socok8s-privileged-cluster-role-binding.yml
    - action: create ceph secrets
      template_src_file: k8s-ses-secrets.yml.j2
      templated_location: /tmp/socok8s-ses-secrets.yml
    - action: create ceph storage class
      template_src_file: k8s-ses-storageclasses.yml.j2
      templated_location: /tmp/socok8s-ses-storage-classes.yml
  tags:
    - run

- name: Updated wait for pods logic to account for stuck k8s jobs
  copy:
    src: wait-for-pods.sh
    dest: /opt/openstack-helm/tools/deployment/common/wait-for-pods.sh
    mode: '0755'
  tags:
    - horizon
    - run


- name: Setup openstack clis
  pip:
    name:
      - cmd2<=0.8.7
      - python-openstackclient
      - python-heatclient

- name: Ensure openstack conf folder exists
  file:
    state: directory
    path: /etc/openstack

- name: Configure clouds.yaml
  copy:
    content: |
      clouds:
        openstack_helm:
          region_name: RegionOne
          identity_api_version: 3
          auth:
            username: 'admin'
            password: 'password'
            project_name: 'admin'
            project_domain_name: 'default'
            user_domain_name: 'default'
            auth_url: 'http://keystone.openstack.svc.cluster.local/v3'
    dest: /etc/openstack/clouds.yaml

# TODO(evrardjp): Follow on https://review.openstack.org/#/c/605005/
- name: Use a different ingress script as long as upstream does not support overrides
  copy:
    src: 020-ingress.sh
    dest: /opt/openstack-helm/tools/deployment/multinode/020-ingress.sh
    mode: '0755'
  tags:
    - ingress
    - run

- name: Template file for the namespaces ingress
  config_template:
    src: ingress-namespace.yaml.j2
    dest: /tmp/socok8s-ingress-namespace.yaml
    config_overrides: "{{ suse_osh_deploy_ingress_namespace_yaml_overrides }}"
    config_type: yaml

- name: Setup Basic ingress and namespace
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: ingress-kube-system.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_ingress_kube_system_yaml_overrides }}"
    _cmpnt_runcommand: ./tools/deployment/multinode/020-ingress.sh
  environment:
    OSH_EXTRA_HELM_ARGS_INGRESS_KUBE_SYSTEM: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_INGRESS_KUBE_SYSTEM') | default('', True) }} --values /tmp/socok8s-ingress-kube-system.yaml"
    OSH_EXTRA_HELM_ARGS_INGRESS_OPENSTACK: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_INGRESS_OPENSTACK') | default('', True) }} --values /tmp/socok8s-ingress-namespace.yaml"
    OSH_EXTRA_HELM_ARGS_INGRESS_CEPH: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_INGRESS_CEPH') | default('', True) }} --values /tmp/socok8s-ingress-namespace.yaml"
  tags:
    - ingress
    - run

- name: Deploy mariadb
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: mariadb.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_mariadb_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/050-mariadb.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_MARIADB: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_MARIADB') | default('', True) }} --values /tmp/socok8s-mariadb.yaml"

- name: Deploy rabbitmq
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: rabbitmq.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_rabbitmq_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/060-rabbitmq.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_RABBITMQ: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_RABBITMQ') | default('', True) }} --values /tmp/socok8s-rabbitmq.yaml"
  tags:
    - rabbitmq
    - run

- name: Deploy memcached
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: memcached.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_memcached_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/070-memcached.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_MEMCACHED: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_MEMCACHED') | default('', True) }} --values /tmp/socok8s-memcached.yaml"
  tags:
    - memcached
    - run

# Keystone should be kept separate as its one failing.
- name: Deploy keystone, ignore errors due to SCRD-4677. #https://jira.suse.de/browse/SCRD-4677.
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: keystone.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_keystone_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/080-keystone.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_KEYSTONE: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_KEYSTONE') | default('', True) }} --values /tmp/socok8s-keystone.yaml"
  tags:
    - keystone
    - run

- name: Use a different horizon script as missing a multinode version without node port requirement
  copy:
    src: 085-horizon.sh
    dest: /opt/openstack-helm/tools/deployment/multinode/085-horizon.sh
    mode: '0755'
  tags:
    - horizon
    - run

- name: Deploy horizon
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: horizon.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_horizon_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/085-horizon.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_HORIZON: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_HORIZON') | default('', True) }} --values /tmp/socok8s-horizon.yaml"
  tags:
    - horizon
    - run

  #TODO(evrardjp): Remove the next two tasks by an appropriate include in tasks/main
  #when https://review.openstack.org/#/c/586992 is merged
- name: Copy ceph provisioner
  template:
    src: 046-ceph-deploy-with-existing-ceph.sh.j2
    dest: "/opt/openstack-helm/tools/deployment/developer/ceph/046-ceph-deploy-with-existing-ceph.sh"
    mode: "0755"
  tags:
    - run

# TODO(evrardjp): Check stdout to ensure idempotency
# Skip ansible linting until idempotency checks are added (changed_when/failed_when)
- name: Execute ceph provisioner
  command: ../openstack-helm/tools/deployment/developer/ceph/046-ceph-deploy-with-existing-ceph.sh
  args:
    executable: /bin/bash
    chdir: /opt/openstack-helm-infra
  tags:
    - run
    - skip_ansible_lint

- name: Deploy glance
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: glance.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_glance_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/100-glance.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_GLANCE: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_GLANCE') | default('', True) }} --values /tmp/socok8s-glance.yaml"
  tags:
    - glance
    - run

# This is an arbitrary UUID value that's passed to the libvirt daemonset setup job for configuring a libvirt secret XML file
- name: Create Libvirt ceph cinder secret uuid
  shell: "uuidgen > {{ socok8s_libvirtuuid }}"
  args:
    creates: "{{ socok8s_libvirtuuid }}"
  delegate_to: localhost

- name: Get libvirt secret
  set_fact:
    libvirt_ceph_cinder_secret_uuid: "{{ lookup('file', socok8s_libvirtuuid) }}"
  run_once: True

- name: Deploy cinder
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: cinder.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_cinder_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/110-cinder.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_CINDER: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_CINDER') | default('', True) }} --values /tmp/socok8s-cinder.yaml"
  tags:
    - cinder
    - run

- name: Deploy OVS
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: ovs.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_ovs_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/120-openvswitch.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_OPENVSWITCH: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_OPENVSWITCH') | default('', True) }} --values /tmp/socok8s-ovs.yaml"
  tags:
    - ovs
    - run

- name: Deploy libvirt
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: libvirt.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_libvirt_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/130-libvirt.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_LIBVIRT: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_LIBVIRT') | default('', True) }} --values /tmp/socok8s-libvirt.yaml"
  tags:
    - libvirt
    - run

# TODO(evrardjp): Check if need to have our own dummy overrides
# In that case, try to split the shell script upstream in two scripts.
# Compute kit deploys nova and neutron but only nova needs overrides
- name: Deploy compute kit
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: nova.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_nova_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/140-compute-kit.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_NOVA: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_NOVA') | default('', True) }} --values /tmp/socok8s-nova.yaml"
  tags:
    - nova
    - neutron
    - run

- name: Deploy Heat
  import_tasks: component-install.yml
  vars:
    _cmpnt_template: heat.yaml
    _cmpnt_overrides: "{{ suse_osh_deploy_heat_yaml_overrides }}"
    _cmpnt_runcommand: "./tools/deployment/multinode/150-heat.sh"
  environment:
    OSH_EXTRA_HELM_ARGS_HEAT: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_HEAT') | default('', True) }} --values /tmp/socok8s-heat.yaml"
  tags:
    - heat
    - run
